main : adj_list.cpp main.cpp 
	g++ main.cpp adj_list.cpp -o main

bfs : adj_list.cpp bfs.cpp
	g++ bfs.cpp adj_list.cpp -o bfs

dfs : adj_list.cpp dfs.cpp
	g++ dfs.cpp adj_list.cpp -o dfs

isConnected : adj_list.cpp isConnected.cpp
	g++ isConnected.cpp adj_list.cpp -o isConnected

map : adj_list_map.cpp
	g++ adj_list_map.cpp -o adj_list_map
